### ISSUE TITLE
Unable to parse private key using v1.0.3 (possible regression)

### ISSUE THREAD

**Issue by drakkan** [kayrus/putty#4]
Hi,

using the ppk from the test cases [here](https://github.com/kayrus/putty/blob/426546c3e80dca5950892d95d3dc127f30a723b6/putty_test.go#L17).

Please try to parse the private key using something like this:

```
key, err := putty.New([]byte(hostKeyRSA2048PPK))
require.NoError(t, err)
_, err = key.ParseRawPrivateKey(nil)
```

it works fine using v1.0.2 but it fails in v1.0.3 with the following error:

```
calculated HMAC "a66962662ca744ad53dec15dd2dd29c8d3397b61" doesn't correspond to "3c3a9bd98e8e912f6163be95321676b6103aaed8"
```

this is likely something related to the password: the `keysFixtures` in test cases seem to contain only password protected private keys. Thank you

**Comment by kayrus** [comment]
@drakkan thanks for submitting a bug report. I released the fix.

**Comment by drakkan** [comment]
it works fine now, thank you
